### PR TITLE
update composer and npm packages to latest versions, fixes security w…

### PR DESCRIPTION
**Pull request by connecteev**
update composer and npm packages to latest versions, fixes security warnings by running 'npm audit fix'

### CODE REVIEW

**Review by the94air — APPROVED** [review]
Thanks, @connecteev.

**Comment by the94air** [comment]
That looks good, but two things left:
1. Run `npm run production`.
2. Force HTTPS on production only:
```php
/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    if (App::environment('production')) {
        URL::forceScheme('https');
    }
}
```

**Comment by the94air** [comment]
@connecteev, Can you add the above edits to the PR so we can merge? Thank you!

**Comment by connecteev** [comment]
@the94air that should be 
```
    if (\App::environment('production')) {
```
otherwise you get
```
In AppServiceProvider.php line 27:
                                       
  Class 'App\Providers\App' not found 
```

**Comment by connecteev** [comment]
@the94air sent..please go ahead and merge

**Review by the94air — APPROVED** [review]
> `if (\App::environment('production')) {`

Yap, forgot about that. Thanks so much.

**Pull request merged**
